### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by walidsa3d** [Munter/ezflix#2]
I get this error when I run the install command : npm ERR! error rolling back Error: Refusing to delete: /usr/local/bin/peerflix not in /usr/local/lib/node_modules/ezflix

**Comment by Munter** [comment]
If you are running on osx and your node has been installed using homebrew, try `npm update -gf` or read this to fix your node installation: https://gist.github.com/DanHerbert/9520689

**Comment by walidsa3d** [comment]
I'm running on ubuntu and I have no problem installing other modules, even those using peerflix.

**Comment by Munter** [comment]
Fixed in ezflix 0.2.1
